tests:
  image: continuumio/miniconda:latest
  tags:
    - linux

  script:
    - conda env update -q --file=environment.yml
    - conda info --envs
    - source activate SPAGAT
    - pip install -e .
    # - pytest --cov=spagat .

pages:
  script:
    - cd doc
    - sphinx-build -d build/doctrees source build/html
    - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master