conda:
  image: continuumio/miniconda:latest
  tags:
    - linux

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - git config --global user.email "l.kotzur@fz-jueich.de"
    - git config --global user.name "Leander Kotzur"
  
  script:
    - conda env update -q --file=environment.yml
    # - conda env update -q --file=environment_dev.yml
    - conda info --envs
    - source activate SPAGAT
    - git clone https://gitlab.version.fz-juelich.de:10022/metis/metis-utils.git
    - pip install -e metis-utils
    - pip install -e .
    - pytest --cov=spagat tests/
