conda:
  image: continuumio/miniconda:latest
  tags:
    - linux

  script:
    - conda env update -q --file=environment.yml
    - conda info --envs
    - source activate SPAGAT
    - pip install -e .
    - pytest --cov=spagat .
