conda:
  image: continuumio/miniconda:latest
  tags: 
  - linux

  script:
    - conda install mamba -c conda-forge
    - mamba create -n fine python=3.6 -y
    - mamba env update -n fine --file=requirements.yml
    - mamba env update -n fine --file=requirements_dev.yml
    - mamba info --envs
    - source activate FINE
    - python -m pip install -e .
    - python -m pytest --cov=FINE test/