image: continuumio/miniconda:latest

cache:
  paths:
    - .pip


before_script:
  - conda env update -q --file=environment.yml
  - conda info --envs
  - source activate SPAGAT
  - pip install -e .

pages:
  script:
    - cd doc
    - sphinx-build -d build/doctrees source build/html
    - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master

tests:
  script:
    - pytest --cov=spagat .
