name: spagat
channels:
  - conda-forge
dependencies:
  - geopandas=0.7
  - jupyter=1
  - matplotlib=3.2
  - numpy
  - pandas=1.0.3
  - pip
  - pytest=5.4
  - scikit-learn
  - tqdm
  - xarray=0.15
  - openpyxl=3.0
  - black=19
