name: SPAGAT
channels:
  - conda-forge
dependencies:
  - dask
  - dask-jobqueue
  - geopandas
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-learn
  - tqdm
  - xarray
  - openpyxl
  - pip:
      - netcdf4
      - pytest-cov
      - scipy
      - sklearn
      - tsam
      - statsmodels
