name: FINE

dependencies:
- python>=3.6,<=3.10
- conda-forge::libiconv
- conda-forge::gdal>2.2.0,<3.0.0
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- conda-forge::libpysal
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd
- pyomo<6.4.2
- numpy<=1.23
- pandas<=1.5
- GPyOpt
- networkx
- scipy
- pwlf
- pyDOE
- sphinx_rtd_theme
- scikit-learn
- xarray
- seaborn
- conda-forge::rasterio
- conda-forge::netcdf4
- conda-forge::tsam
- wquantiles
- cython

- pip:
    - .