name: FINE
dependencies:
- python=3.6
- gdal=2.3.3
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd
- pyomo
- numpy
- pandas
- pip:
    - https://github.com/FZJ-IEK3-VSA/geokit/archive/gdal_relax.zip
  