name: FINE
dependencies:
- python=3.6
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd
- pyomo
- numpy
- pandas
- xarray
- GPyOpt
- networkx
- scipy
- pwlf
- pyDOE
- sphinx_rtd_theme
- scikit-learn
- pip:
    - tsam