name: FINE
dependencies:
- python=3.6
- gdal=2.3.3
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd
- pyomo
- numpy
- pandas