name: FINE
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.6
- conda-forge::geopandas
- conda-forge::jupyter
- conda-forge::notebook
- pip
- descartes
- glpk
- openpyxl
- matplotlib
- xlrd
- pyomo
- numpy
- pandas
- xarray
- GPyOpt
- networkx
- scipy
